title: "Raunit Kohli - ML Engineer & Researcher"
url: "https://www.raunitkohli.com"
baseurl: ""

author:
  name: "Raunit Kohli"
  email: "raunitkohli@gmail.com"  # Verify this is correct email
  url: "https://kohlir2020.github.io"

social:
  github: "kohlir2020"
  linkedin: "in/raunit-kohli"  # Verify LinkedIn username

# Additional SEO settings
lang: en_US
timezone: America/New_York  # Adjust timezone as needed
