title: Raunit Kohli
description: Machine Learning Software Engineer and Researcher specializing in Reinforcement Learning, Computer Vision, and AI applications. Experienced in robotics, data science, and innovative ML solutions.
url: https://kohlir2020.github.io
baseurl: ""
theme: jekyll-theme-cayman

social:
  name: Raunit Kohli
  links:
    - https://www.linkedin.com/in/yourprofile
    - https://github.com/kohlir2020